service: eatery-explorer-backend

provider:
    name: aws
    runtime: nodejs20.x
    region: eu-west-2
    stage: ${opt:stage, 'prod'}
    deploymentMethod: direct
    stackName: eatery-explorer-backend-${self:provider.stage}
    environment:
        NODE_ENV: production # Set environment variables

functions:
    app:
        handler: app.handler
        events:
            - http:
                  path: /
                  method: ANY
            - http:
                  path: /{proxy+}
                  method: ANY
